(straight-use-package 'catppuccin-theme)

(require 'catppuccin-theme)
(catppuccin-set-color 'rosewater "#f5e0dc")
(catppuccin-set-color 'flamingo "#f2cdcd")
(catppuccin-set-color 'pink "#f5c2e7")
(catppuccin-set-color 'mauve "#cba6f7")
(catppuccin-set-color 'red "#ff1688")
(catppuccin-set-color 'maroon "#ff629d")
(catppuccin-set-color 'peach "#fab387")
(catppuccin-set-color 'yellow "#ffcc11")
(catppuccin-set-color 'green "#a6e3a1")
(catppuccin-set-color 'teal "#94e2d5")
(catppuccin-set-color 'sky "#89dceb")
(catppuccin-set-color 'sapphire "#74c7ec")
(catppuccin-set-color 'blue "#47c8c0")
(catppuccin-set-color 'lavender "#b4befe")
(catppuccin-set-color 'text "#d6d9da")
(catppuccin-set-color 'subtext1 "#adb3b5")
(catppuccin-set-color 'subtext0 "#9ca4a6")
(catppuccin-set-color 'overlay2 "#8c9597")
(catppuccin-set-color 'overlay1 "#7b8589")
(catppuccin-set-color 'overlay0 "#6b767a")
(catppuccin-set-color 'surface2 "#5a676b")
(catppuccin-set-color 'surface1 "#465053")
(catppuccin-set-color 'surface0 "#3c4547")
(catppuccin-set-color 'base "#282e2f")
(catppuccin-set-color 'mantle "#1e2223")
(catppuccin-set-color 'crust "#090a0b")
(catppuccin-reload)
