(load-relative "./plugins/evil.el")
(load-relative "./plugins/company.el")
;; (load-relative "./plugins/dashboard.el")
(load-relative "./plugins/options.el")
(load-relative "./plugins/others.el")
(load-relative "./plugins/projectile.el")
;; (load-relative "./plugins/dirvish.el")
;; (load-relative "./plugins/treemacs.el")
(load-relative "./plugins/neotree.el")
(load-relative "./plugins/which-key.el")
(load-relative "./plugins/doom-modeline.el")
(load-relative "./plugins/multiple-cursors.el")
(load-relative "./plugins/theme.el")
(load-relative "./plugins/tabs.el")
(load-relative "./plugins/lsp.el")
(load-relative "./plugins/yn.el")
(load-relative "./plugins/keybinds.el")
